services:
  - type: web
    name: discord-voice-rewards-bot
    env: python
    runtime: python-3.11
    buildCommand: "bash render_build.sh"
    startCommand: "bash render_start.sh"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: API_BASE_URL
        value: https://api.gtps.cloud/g-api/1782
      - key: VP_CHANNEL_ID
        value: "1470057279511466045"
      - key: GEMS_CHANNEL_ID
        value: "1470057299631411444"
